name: flutter_allears

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.2
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.1.7
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.3
  flutter_dotenv: ^5.0.2
  package_info_plus: ^8.3.1
